[package]
name = "intermpdf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mupdf = "0.4.2"
nix = { version = "0.28.0", features = ["term", "ioctl"] }
openssl = "0.10.64"
